version: "3.7"

services:

  frontend:
    build:
      context: ./frontend/
    command: "npm run dev"
    restart: always
    networks:
      - front-tier

  backend:
    build:
      context: ./backend/
    command: "flask run --host=0.0.0.0"
    networks:
      - back-tier
    restart: always
  mongo:
    image: mongo
    command: --serviceExecutor adaptive
    restart: always
    volumes:
      - ./mongodb:/data/db
    networks:
      - back-tier

  redis:
    image: 'redis'
    volumes:
      - ./redis:/var/lib/redis
    networks:
      - back-tier

  nginx:
    restart: always
    build:
      context: ./nginx/
    ports:
    - "80:80"
    - "5000:5000"
    networks:
      - front-tier
      - back-tier


networks:
  front-tier:
  back-tier: